[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = ["pytest>=9.0.2", "ruff>=0.15.4"]

[project]
name = "mzn-bench"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Jip J. Dekker", email = "jip@dekker.one" }]
requires-python = ">=3.10"
dependencies = ["click>=8.3.1", "minizinc>=0.10.0", "ruamel-yaml>=0.19.1"]

[project.scripts]
mzn-bench = 'mzn_bench.cli:main'

[project.optional-dependencies]
scripts = ["pandas>=2.2.3", "pytest>=9.0.2", "tabulate>=0.9.0"]
plotting = ["bokeh>=3.6.2", "matplotlib>=3.10.1", "seaborn>=0.13.2"]
